name: blog auto-deploy

on:
  # 每当 push 到 master 分支时触发部署
  push:
    branches: [master]
  # 手动触发部署
  workflow_dispatch:

#任务
jobs:
  blog: # 一个job任务，任务名为blog
    runs-on: ubuntu-latest # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # 选择要使用的 node 版本
          node-version: "14"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      # 缓存 node_modules
      - name: Cache ~/.pnpm-store
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-preview-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-preview-${{ env.cache-name }}-
            ${{ runner.os }}-preview-
            ${{ runner.os }}-

      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 运行构建脚本
      - name: Build VuePress site
        run: pnpm build
        env:
          DOC_ENV: preview

      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 gh-pages 分支
          target_branch: gh-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: .vuepress/dist
        env:
          # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
